version: "2"
services:
  api:
    image: dcard:1.1
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - cache
    command: node ./app.js
    environment:
      REDISHOST: cache
      REDISPORT: 6379
  cache:
    image: redis
    ports:
      - 6379:6379